export const AMENITIES = "AMENITIES";

export const FLOWER_PROXIMITY = [5, 10, 15];

export const AMENITIES_LIST = [
  "Mobilitaetspunkte",
  "atm",
  "bakery",
  "bank",
  "bar",
  "bike_sharing",
  "bus_stop",
  "butcher",
  "cafe",
  "car_sharing",
  "charging_station",
  "cinema",
  "convenience",
  "dentist",
  "discount_supermarket",
  "fast_food",
  "general_practitioner",
  "grundschule",
  "gym",
  "gymnasium",
  "hauptschule_mittelschule",
  "hotel",
  "kindergarten",
  "marketplace",
  "museum",
  "nursery",
  "organic_supermarket",
  "park",
  "pharmacy",
  "playground",
  "population",
  "post_box",
  "post_office",
  "pub",
  "realschule",
  "recycling",
  "restaurant",
  "subway_entrance",
  "supermarket",
  "tram_stop",
];
