export const AMENITIES = "AMENITIES";

export const FLOWER_PROXIMITY = [5, 10, 15];

export const AMENITIES_LIST = [
  "Mobilitaetspunkte",
  "atm",
  "bakery",
  "bank",
  "bar",
  "bike_sharing",
  "bus_stop",
  "butcher",
  "cafe",
  "car_sharing",
  "charging_station",
  "cinema",
  "convenience",
  "dentist",
  "discount_supermarket",
  "fast_food",
  "general_practitioner",
  "grundschule",
  "gym",
  "gymnasium",
  "hauptschule_mittelschule",
  "hotel",
  "kindergarten",
  "marketplace",
  "museum",
  "nursery",
  "organic_supermarket",
  "park",
  "pharmacy",
  "playground",
  "population",
  "post_box",
  "post_office",
  "pub",
  "realschule",
  "recycling",
  "restaurant",
  "subway_entrance",
  "supermarket",
  "tram_stop",
];

export const AMENITIES_GROUP = {
  food: ["restaurant", "fast_food", "cafe", "pub", "bar"],
  transport: ["bus_stop", "tram_stop", "bike_sharing", "car_sharing", "charging_station"],
  health: ["dentist", "general_practitioner", "pharmacy"],
  services: ["atm", "bank", "post_office", "post_box"],
  sport: ["gym", "yoga"],
  nature: ["park"],
  tourism: ["cinema", "museum", "hotel", "playground"],
  shop: [
    "organic_supermarket",
    "discount_supermarket",
    "supermarket",
    "hyper",
    "marketplace",
    "bakery",
    "butcher",
  ],
  education: [
    "kindergarten",
    "hauptschule_mittelschule",
    "grundschule",
    "realschule",
    "gymnasium",
  ],
};
