name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm i
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run the react app
        run: pnpm dev
      - name: Run Playwright tests
        run: pnpm dlx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
